# Generated by Django 2.2.7 on 2019-11-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_medicalpratitioner_sickuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalPratitioner',
            new_name='MedicalPractitioner',
        ),
    ]
