# Generated by Django 2.2.7 on 2019-11-21 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191120_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalpractitioner',
            name='myuser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user name'),
        ),
    ]
