# Generated by Django 2.2.7 on 2019-11-20 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20191120_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurementData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Height (m)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight (Kg)')),
                ('myuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.SickUser')),
            ],
        ),
        migrations.CreateModel(
            name='BloodData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=5)),
                ('genotype', models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('AC', 'AC')], max_length=5)),
                ('myuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.SickUser')),
            ],
        ),
    ]
