# Generated by Django 2.2.7 on 2019-11-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_hospitallocation_medicaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldata',
            name='test_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hospitallocation',
            name='sickuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sickuser_hospital_location', to='users.SickUser'),
        ),
        migrations.AlterField(
            model_name='medicaldata',
            name='sickuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sickuser_data', to='users.SickUser'),
        ),
    ]
